# Generated by Django 5.1.6 on 2025-07-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorizationlog',
            name='final_category',
        ),
        migrations.RemoveField(
            model_name='categorizationlog',
            name='rule_used',
        ),
        migrations.RemoveField(
            model_name='categorizationlog',
            name='suggested_category',
        ),
        migrations.RemoveField(
            model_name='categorizationlog',
            name='transaction',
        ),
        migrations.AlterUniqueTogether(
            name='categoryperformance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='categoryperformance',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryperformance',
            name='company',
        ),
        migrations.RemoveField(
            model_name='categoryrule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryrule',
            name='company',
        ),
        migrations.RemoveField(
            model_name='categoryrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='categorysuggestion',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='categorysuggestion',
            name='suggested_category',
        ),
        migrations.RemoveField(
            model_name='categorysuggestion',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='AITrainingData',
        ),
        migrations.DeleteModel(
            name='CategorizationLog',
        ),
        migrations.DeleteModel(
            name='CategoryPerformance',
        ),
        migrations.DeleteModel(
            name='CategoryRule',
        ),
        migrations.DeleteModel(
            name='CategorySuggestion',
        ),
    ]
