# Generated by Django 5.1.6 on 2025-07-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitrainingdata',
            name='verification_source',
            field=models.CharField(choices=[('manual', 'Revisão Manual'), ('user_feedback', 'Feedback do Usuário'), ('rule_based', 'Baseado em Regras'), ('ai_confident', 'IA Alta Confiança')], default='manual', max_length=20, verbose_name='verification source'),
        ),
        migrations.AlterField(
            model_name='categorizationlog',
            name='method',
            field=models.CharField(choices=[('ai', 'Predição IA'), ('rule', 'Baseado em Regras'), ('manual', 'Manual'), ('bulk', 'Operação em Massa'), ('recurring', 'Padrão Recorrente')], max_length=20, verbose_name='categorization method'),
        ),
    ]
