[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[deploy.preDeploy]]
command = "python manage.py ensure_database"

[[deploy.preDeploy]]
command = "python manage.py migrate --no-input"