[build]
builder = "dockerfile"

[deploy]
startCommand = "python manage.py migrate && python manage.py seed_plans && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
healthcheckPath = "/api/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[experimental]
nixpacks = false