[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.environment]
DJANGO_SETTINGS_MODULE = "core.settings.production"

# Pre-deploy commands are handled in start.sh for better control