# Generated by Django 5.1.6 on 2025-07-29 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='email notifications')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='push notifications')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS notifications')),
                ('type_preferences', models.JSONField(default=dict, verbose_name='type preferences')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='quiet hours end')),
                ('send_daily_digest', models.BooleanField(default=False, verbose_name='send daily digest')),
                ('send_weekly_digest', models.BooleanField(default=True, verbose_name='send weekly digest')),
                ('digest_time', models.TimeField(default='09:00', verbose_name='digest time')),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=1000.0, max_digits=15, verbose_name='low balance threshold')),
                ('large_transaction_threshold', models.DecimalField(decimal_places=2, default=5000.0, max_digits=15, verbose_name='large transaction threshold')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_balance', 'Saldo Baixo'), ('large_transaction', 'Transação Grande'), ('recurring_payment', 'Pagamento Recorrente'), ('sync_error', 'Erro de Sincronização'), ('report_ready', 'Relatório Pronto'), ('subscription_expiring', 'Assinatura Expirando'), ('user_invited', 'Usuário Convidado'), ('budget_exceeded', 'Orçamento Excedido'), ('ai_insight', 'Insight IA'), ('custom', 'Personalizado')], max_length=30, verbose_name='notification type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('data', models.JSONField(default=dict, verbose_name='additional data')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='action URL')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='priority')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='email sent at')),
                ('push_sent', models.BooleanField(default=False, verbose_name='push sent')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='push sent at')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS sent')),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='SMS sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['company', 'created_at'], name='notificatio_company_b64cff_idx'), models.Index(fields=['notification_type', 'is_read'], name='notificatio_notific_72d27e_idx'), models.Index(fields=['priority', 'created_at'], name='notificatio_priorit_22e6c2_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
