"""
Management command to initialize security components
"""
from django.core.management.base import BaseCommand
from django.conf import settings
import os


class Command(BaseCommand):
    help = 'Initialize security components including JWT keys'
    
    def add_arguments(self, parser):
        parser.add_argument(
            '--force-key-rotation',
            action='store_true',
            help='Force rotation of existing JWT keys'
        )
        parser.add_argument(
            '--setup-production',
            action='store_true',
            help='Setup production security configuration'
        )
    
    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('🔐 Initializing Security Components'))
        
        # Initialize JWT keys
        self._initialize_jwt_keys(options['force_key_rotation'])
        
        # Setup production security if requested
        if options['setup_production']:
            self._setup_production_security()
        
        # Verify security configuration
        self._verify_security_config()
        
        self.stdout.write(self.style.SUCCESS('✅ Security initialization completed'))
    
    def _initialize_jwt_keys(self, force_rotation=False):
        """Initialize JWT RSA keys"""
        self.stdout.write('📋 Initializing JWT keys...')
        
        try:
            from core.security.jwt_keys import jwt_key_manager
            
            if force_rotation:
                jwt_key_manager.rotate_keys()
                self.stdout.write(self.style.WARNING('🔄 JWT keys rotated'))
            else:
                keys_created = jwt_key_manager.ensure_keys_exist()
                if keys_created:
                    self.stdout.write(self.style.SUCCESS('🔑 New JWT keys generated'))
                else:
                    self.stdout.write('🔑 JWT keys already exist')
            
            # Test key loading
            private_key = jwt_key_manager.load_private_key()
            public_key = jwt_key_manager.load_public_key()
            
            self.stdout.write(f'   Private key size: {len(private_key)} bytes')
            self.stdout.write(f'   Public key size: {len(public_key)} bytes')
            
        except Exception as e:
            self.stdout.write(
                self.style.ERROR(f'❌ Failed to initialize JWT keys: {e}')
            )
            raise
    
    def _setup_production_security(self):
        """Setup production security configuration"""
        self.stdout.write('🏭 Setting up production security...')
        
        security_settings = {
            'SECURE_SSL_REDIRECT': True,
            'SECURE_HSTS_SECONDS': 31536000,  # 1 year
            'SECURE_HSTS_INCLUDE_SUBDOMAINS': True,
            'SECURE_HSTS_PRELOAD': True,
            'SESSION_COOKIE_SECURE': True,
            'CSRF_COOKIE_SECURE': True,
            'SECURE_BROWSER_XSS_FILTER': True,
            'SECURE_CONTENT_TYPE_NOSNIFF': True,
        }
        
        config_path = os.path.join(settings.BASE_DIR, 'core', 'settings', 'production_security.py')
        
        try:
            with open(config_path, 'w') as f:
                f.write('# Production Security Settings\n')
                f.write('# Generated by init_security command\n\n')
                
                for setting, value in security_settings.items():
                    f.write(f'{setting} = {repr(value)}\n')
                
                f.write('\n# Additional Security Headers\n')
                f.write('SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"\n')
                f.write('SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"\n')
            
            self.stdout.write(f'   Created: {config_path}')
            self.stdout.write('   Import this file in production.py settings')
            
        except Exception as e:
            self.stdout.write(
                self.style.ERROR(f'❌ Failed to create production security config: {e}')
            )
    
    def _verify_security_config(self):
        """Verify security configuration"""
        self.stdout.write('🔍 Verifying security configuration...')
        
        checks = [
            ('JWT Algorithm', lambda: getattr(settings, 'SIMPLE_JWT', {}).get('ALGORITHM') == 'RS256'),
            ('Enhanced Auth Backend', lambda: 'apps.authentication.backends.EnhancedAuthenticationBackend' in settings.AUTHENTICATION_BACKENDS),
            ('Security Middleware', lambda: 'apps.authentication.middleware.SecurityMiddleware' in settings.MIDDLEWARE),
            ('Password Validators', lambda: any('ComprehensivePasswordValidator' in str(v) for v in settings.AUTH_PASSWORD_VALIDATORS)),
            ('Rate Limiting', lambda: getattr(settings, 'RATELIMIT_ENABLE', False)),
            ('Session Security', lambda: settings.SESSION_COOKIE_HTTPONLY),
        ]
        
        passed = 0
        for check_name, check_func in checks:
            try:
                if check_func():
                    self.stdout.write(f'   ✅ {check_name}')
                    passed += 1
                else:
                    self.stdout.write(f'   ❌ {check_name}')
            except Exception as e:
                self.stdout.write(f'   ⚠️  {check_name}: {e}')
        
        self.stdout.write(f'📊 Security checks: {passed}/{len(checks)} passed')
        
        if passed < len(checks):
            self.stdout.write(
                self.style.WARNING('⚠️  Some security checks failed. Review your configuration.')
            )
    
    def _check_environment_variables(self):
        """Check for required environment variables"""
        self.stdout.write('🌍 Checking environment variables...')
        
        required_vars = [
            'SECRET_KEY',
            'DATABASE_URL',
            'REDIS_URL',
        ]
        
        optional_vars = [
            'JWT_SECRET_KEY',
            'ENCRYPTION_KEY',
            'SENTRY_DSN',
        ]
        
        missing_required = []
        missing_optional = []
        
        for var in required_vars:
            if not os.environ.get(var):
                missing_required.append(var)
            else:
                self.stdout.write(f'   ✅ {var}')
        
        for var in optional_vars:
            if not os.environ.get(var):
                missing_optional.append(var)
            else:
                self.stdout.write(f'   ✅ {var}')
        
        if missing_required:
            self.stdout.write(
                self.style.ERROR(f'❌ Missing required variables: {", ".join(missing_required)}')
            )
        
        if missing_optional:
            self.stdout.write(
                self.style.WARNING(f'⚠️  Missing optional variables: {", ".join(missing_optional)}')
            )
    
    def _test_security_components(self):
        """Test security components"""
        self.stdout.write('🧪 Testing security components...')
        
        try:
            # Test rate limiter
            from apps.authentication.security.rate_limiting import ProgressiveRateLimiter
            rate_limiter = ProgressiveRateLimiter('test')
            self.stdout.write('   ✅ Rate limiter')
            
            # Test password validator
            from apps.authentication.security.password_policies import ComprehensivePasswordValidator
            validator = ComprehensivePasswordValidator()
            self.stdout.write('   ✅ Password validator')
            
            # Test session manager
            from apps.authentication.security.session_management import SessionManager
            session_manager = SessionManager()
            self.stdout.write('   ✅ Session manager')
            
            # Test anomaly detector
            from apps.authentication.security.anomaly_detection import AnomalyDetector
            detector = AnomalyDetector()
            self.stdout.write('   ✅ Anomaly detector')
            
        except Exception as e:
            self.stdout.write(
                self.style.ERROR(f'❌ Security component test failed: {e}')
            )