# Generated by Django 5.1.6 on 2025-08-05 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0012_add_notification_fields'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('AUTH_LOGIN', 'User Login'), ('AUTH_LOGOUT', 'User Logout'), ('AUTH_FAILED_LOGIN', 'Failed Login Attempt'), ('AUTH_PASSWORD_CHANGE', 'Password Changed'), ('AUTH_PASSWORD_RESET', 'Password Reset'), ('AUTH_2FA_ENABLED', '2FA Enabled'), ('AUTH_2FA_DISABLED', '2FA Disabled'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('COMPANY_CREATED', 'Company Created'), ('COMPANY_UPDATED', 'Company Updated'), ('COMPANY_DELETED', 'Company Deleted'), ('PAYMENT_CREATED', 'Payment Created'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated'), ('SUBSCRIPTION_CANCELLED', 'Subscription Cancelled'), ('BANK_ACCOUNT_CONNECTED', 'Bank Account Connected'), ('BANK_ACCOUNT_DISCONNECTED', 'Bank Account Disconnected'), ('BANK_SYNC_STARTED', 'Bank Sync Started'), ('BANK_SYNC_COMPLETED', 'Bank Sync Completed'), ('BANK_SYNC_FAILED', 'Bank Sync Failed'), ('TRANSACTION_CREATED', 'Transaction Created'), ('TRANSACTION_UPDATED', 'Transaction Updated'), ('TRANSACTION_DELETED', 'Transaction Deleted'), ('TRANSACTION_CATEGORIZED', 'Transaction Categorized'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_EXPORTED', 'Report Exported'), ('AI_REQUEST', 'AI Request Made'), ('AI_RESPONSE', 'AI Response Received'), ('DATA_EXPORT', 'Data Exported'), ('DATA_IMPORT', 'Data Imported'), ('SECURITY_ALERT', 'Security Alert'), ('PERMISSION_DENIED', 'Permission Denied'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='companies.company')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog', 
            index=models.Index(fields=['event_type', 'timestamp'], name='audit_logs_event_t_b9d8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_39f9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'timestamp'], name='audit_logs_company_3f7a29_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_2a6c4f_idx'),
        ),
    ]
