# Generated by Django 5.1.6 on 2025-08-12 01:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('AUTH_LOGIN', 'User Login'), ('AUTH_LOGOUT', 'User Logout'), ('AUTH_FAILED_LOGIN', 'Failed Login Attempt'), ('AUTH_PASSWORD_CHANGE', 'Password Changed'), ('AUTH_PASSWORD_RESET', 'Password Reset'), ('AUTH_2FA_ENABLED', '2FA Enabled'), ('AUTH_2FA_DISABLED', '2FA Disabled'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('COMPANY_CREATED', 'Company Created'), ('COMPANY_UPDATED', 'Company Updated'), ('COMPANY_DELETED', 'Company Deleted'), ('PAYMENT_CREATED', 'Payment Created'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated'), ('SUBSCRIPTION_CANCELLED', 'Subscription Cancelled'), ('BANK_ACCOUNT_CONNECTED', 'Bank Account Connected'), ('BANK_ACCOUNT_DISCONNECTED', 'Bank Account Disconnected'), ('BANK_SYNC_STARTED', 'Bank Sync Started'), ('BANK_SYNC_COMPLETED', 'Bank Sync Completed'), ('BANK_SYNC_FAILED', 'Bank Sync Failed'), ('TRANSACTION_CREATED', 'Transaction Created'), ('TRANSACTION_UPDATED', 'Transaction Updated'), ('TRANSACTION_DELETED', 'Transaction Deleted'), ('TRANSACTION_CATEGORIZED', 'Transaction Categorized'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_EXPORTED', 'Report Exported'), ('AI_REQUEST', 'AI Request Made'), ('AI_RESPONSE', 'AI Response Received'), ('DATA_EXPORT', 'Data Exported'), ('DATA_IMPORT', 'Data Imported'), ('SECURITY_ALERT', 'Security Alert'), ('PERMISSION_DENIED', 'Permission Denied'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
