# Generated by Django 4.2.11 on 2025-09-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_gateway',
        ),
    ]
