# Generated by Django 5.1.6 on 2025-08-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_emai_476443_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
