# Generated by Django 5.0.1 on 2025-06-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_backup_codes_user_is_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='payment customer ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='payment gateway'),
        ),
    ]
