# Generated by Django 4.2.11 on 2025-11-15 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_payment_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('bank_connection_created', 'Bank Connection Created'), ('bank_connection_updated', 'Bank Connection Updated'), ('bank_connection_deleted', 'Bank Connection Deleted'), ('sync_started', 'Sync Started'), ('sync_completed', 'Sync Completed'), ('sync_failed', 'Sync Failed'), ('password_reset_requested', 'Password Reset Requested'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated')], db_index=True, max_length=50, verbose_name='event type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_activi_user_id_543519_idx'), models.Index(fields=['event_type', '-created_at'], name='user_activi_event_t_55cb55_idx'), models.Index(fields=['user', 'event_type', '-created_at'], name='user_activi_user_id_d4d80d_idx')],
            },
        ),
    ]
