# Generated by Django 5.1.6 on 2025-08-20 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='verification token')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'db_table': 'email_verifications',
                'indexes': [models.Index(fields=['user', 'is_used'], name='email_verif_user_id_f77c27_idx'), models.Index(fields=['token'], name='email_verif_token_403404_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_fdd67c_idx')],
            },
        ),
    ]
