# Generated by Django 5.1.6 on 2025-07-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_payment_customer_id_user_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_customer_id',
            field=models.CharField(blank=True, help_text='ID do cliente no gateway de pagamento (Stripe/MercadoPago)', max_length=255, null=True, verbose_name='payment gateway customer ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('mercadopago', 'MercadoPago')], help_text='Gateway de pagamento utilizado', max_length=50, null=True, verbose_name='payment gateway'),
        ),
    ]
