# Generated by Django 4.2.11 on 2025-11-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID da landing page onde o usuário se cadastrou', max_length=100, null=True, verbose_name='signup price ID'),
        ),
    ]
