# Generated by Django 5.1.6 on 2025-07-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Inicial'), ('professional', 'Profissional'), ('enterprise', 'Empresarial')], max_length=20, verbose_name='plan type'),
        ),
    ]
