# Generated by Django 5.0.1 on 2025-06-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='subscription end date'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subscription ID'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='subscription start date'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='gateway_plan_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='payment gateway plan ID'),
        ),
    ]
