# Generated by Django 4.2.11 on 2025-09-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_sector',
            field=models.CharField(choices=[('retail', 'Comércio'), ('services', 'Serviços'), ('industry', 'Indústria'), ('technology', 'Tecnologia'), ('healthcare', 'Saúde'), ('education', 'Educação'), ('food', 'Alimentação'), ('construction', 'Construção'), ('automotive', 'Automotivo'), ('agriculture', 'Agricultura'), ('other', 'Outros')], default='default', max_length=50, verbose_name='business sector'),
        ),
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(default='default', max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('mei', 'MEI'), ('me', 'Microempresa'), ('epp', 'Empresa de Pequeno Porte'), ('ltda', 'Limitada'), ('sa', 'Sociedade Anônima'), ('other', 'Outros')], default='default', max_length=20, verbose_name='company type'),
        ),
    ]
