# Generated by Django 4.2.11 on 2025-09-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_business_sector_company_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='company',
            name='current_month_transactions',
        ),
        migrations.RemoveField(
            model_name='company',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='company',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='trial_ends_at',
        ),
        migrations.AlterField(
            model_name='company',
            name='business_sector',
            field=models.CharField(choices=[('retail', 'Comércio'), ('services', 'Serviços'), ('industry', 'Indústria'), ('technology', 'Tecnologia'), ('healthcare', 'Saúde'), ('education', 'Educação'), ('food', 'Alimentação'), ('construction', 'Construção'), ('automotive', 'Automotivo'), ('agriculture', 'Agricultura'), ('other', 'Outros')], max_length=50, verbose_name='business sector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(help_text='CNPJ no formato XX.XXX.XXX/XXXX-XX', max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('mei', 'MEI'), ('me', 'Microempresa'), ('epp', 'Empresa de Pequeno Porte'), ('ltda', 'Limitada'), ('sa', 'Sociedade Anônima'), ('other', 'Outros')], max_length=20, verbose_name='company type'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('cnpj',), name='unique_active_cnpj'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
