# Generated by Django 5.1.6 on 2025-07-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Período de Teste'), ('active', 'Ativa'), ('past_due', 'Em Atraso'), ('cancelled', 'Cancelada'), ('suspended', 'Suspensa')], default='trial', max_length=20, verbose_name='subscription status'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Inicial'), ('pro', 'Profissional'), ('enterprise', 'Empresarial')], max_length=20, verbose_name='plan type'),
        ),
    ]
