# Generated by Django 5.1.6 on 2025-07-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_simplify'),
        ('companies', '0003_consolidate_subscriptions'),
    ]

    operations = [
    ]
