# Generated by Django 5.1.6 on 2025-07-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_subscriptionplan_trial_days_and_more'),
        ('companies', '0003_remove_free_plan'),
    ]

    operations = [
    ]
