# Generated by Django 5.1.6 on 2025-07-10 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_subscription_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('pix', 'PIX'), ('bank_transfer', 'Transferência Bancária')], max_length=20, verbose_name='payment type')),
                ('card_brand', models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('elo', 'Elo'), ('dinners', 'Dinners Club'), ('discover', 'Discover')], max_length=20, verbose_name='card brand')),
                ('last_four', models.CharField(blank=True, max_length=4, verbose_name='last four digits')),
                ('exp_month', models.IntegerField(blank=True, null=True, verbose_name='expiry month')),
                ('exp_year', models.IntegerField(blank=True, null=True, verbose_name='expiry year')),
                ('cardholder_name', models.CharField(blank=True, max_length=200, verbose_name='cardholder name')),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe payment method ID')),
                ('mercadopago_card_id', models.CharField(blank=True, max_length=255, verbose_name='MercadoPago card ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='companies.company')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('subscription', 'Assinatura'), ('upgrade', 'Upgrade de Plano'), ('refund', 'Reembolso'), ('adjustment', 'Ajuste')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('canceled', 'Cancelado'), ('refunded', 'Reembolsado'), ('partially_refunded', 'Parcialmente Reembolsado')], max_length=20, verbose_name='status')),
                ('description', models.TextField(verbose_name='description')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe payment intent ID')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe invoice ID')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=255, verbose_name='MercadoPago payment ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='invoice number')),
                ('invoice_url', models.URLField(blank=True, verbose_name='invoice URL')),
                ('invoice_pdf_path', models.CharField(blank=True, max_length=500, verbose_name='invoice PDF path')),
                ('transaction_date', models.DateTimeField(verbose_name='transaction date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='companies.company')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.subscriptionplan')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.paymentmethod')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment History',
                'db_table': 'payment_history',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
