# Generated by Django 5.1.6 on 2025-07-16 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge_20250715_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month', verbose_name='month')),
                ('transactions_count', models.IntegerField(default=0, verbose_name='transactions count')),
                ('ai_requests_count', models.IntegerField(default=0, verbose_name='AI requests count')),
                ('reports_generated', models.IntegerField(default=0, verbose_name='reports generated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_usage', to='companies.company')),
            ],
            options={
                'verbose_name': 'Resource Usage',
                'verbose_name_plural': 'Resource Usage',
                'db_table': 'resource_usage',
                'ordering': ['-month'],
                'unique_together': {('company', 'month')},
            },
        ),
    ]
