# Generated by Django 5.1.6 on 2025-07-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_paymentmethod_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='enable_ai_insights',
            field=models.BooleanField(default=True, verbose_name='AI insights'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='enable_ai_reports',
            field=models.BooleanField(default=False, verbose_name='AI reports'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_ai_requests_per_month',
            field=models.IntegerField(default=100, verbose_name='max AI requests per month'),
        ),
    ]
