# Generated by Django 5.1.6 on 2025-07-19 02:06
# FAKE migration - field already removed

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_resourceusage'),
    ]

    operations = [
        # Field max_users already removed from model
        # This is a placeholder migration to maintain dependency chain
    ]