# Generated by Django 5.1.6 on 2025-07-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_resourceusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_users',
        ),
    ]
