# Generated by Django 5.1.6 on 2025-07-14 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_subscriptionplan_enable_ai_insights_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['display_order', 'price_monthly'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='gateway_plan_id',
        ),
        migrations.AddField(
            model_name='company',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='billing cycle'),
        ),
        migrations.AddField(
            model_name='company',
            name='current_month_ai_requests',
            field=models.IntegerField(default=0, verbose_name='current month AI requests'),
        ),
        migrations.AddField(
            model_name='company',
            name='current_month_transactions',
            field=models.IntegerField(default=0, verbose_name='current month transactions'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_usage_reset',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='last usage reset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='notified_80_percent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='notified_90_percent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='display order'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_priority_support',
            field=models.BooleanField(default=False, verbose_name='priority support'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='mercadopago_plan_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='MercadoPago plan ID'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe price ID'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Período de Teste'), ('active', 'Ativa'), ('past_due', 'Em Atraso'), ('cancelled', 'Cancelada'), ('suspended', 'Suspensa'), ('expired', 'Expirada')], default='trial', max_length=20, verbose_name='subscription status'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Grátis'), ('starter', 'Inicial'), ('professional', 'Profissional'), ('enterprise', 'Empresarial')], max_length=20, verbose_name='plan type'),
        ),
    ]
