# Generated by Django 5.1.6 on 2025-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_max_users_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='gateway_plan_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_price_id',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, help_text='price_xxx do Stripe para cobrança mensal', max_length=255, verbose_name='Stripe monthly price ID'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, help_text='price_xxx do Stripe para cobrança anual', max_length=255, verbose_name='Stripe yearly price ID'),
        ),
    ]
