# Generated by Django 5.1.6 on 2025-07-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDashboardProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard de Faturamento',
                'verbose_name_plural': 'Dashboard de Faturamento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('companies.company',),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='gateway_plan_id',
            field=models.CharField(blank=True, help_text='ID do plano/preço no gateway de pagamento (Stripe/MercadoPago)', max_length=255, verbose_name='payment gateway plan ID'),
        ),
    ]
