# Generated by Django 5.1.6 on 2025-07-21 19:38
# FAKE migration - fields already exist

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_max_users_field'),
    ]

    operations = [
        # Fields already exist in database
        # This is a placeholder migration to maintain dependency chain
    ]