# Generated by Django 5.1.6 on 2025-07-22 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_add_stripe_price_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['subscription_plan', 'subscription_status'], name='companies_subscri_f72d81_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['subscription_status', 'trial_ends_at'], name='companies_subscri_c1c1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['next_billing_date', 'subscription_status'], name='companies_next_bi_dfccba_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['last_usage_reset', 'is_active'], name='companies_last_us_3ace5b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['current_month_transactions', 'subscription_plan'], name='companies_current_5a978d_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['current_month_ai_requests', 'subscription_plan'], name='companies_current_87a2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['cnpj'], name='companies_cnpj_0deb88_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'created_at'], name='companies_is_acti_3ffea8_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_type', 'business_sector'], name='companies_company_835af2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['company', 'transaction_date'], name='payment_his_company_e9ccab_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['company', 'status', 'transaction_date'], name='payment_his_company_441891_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['company', 'transaction_type'], name='payment_his_company_2c6f04_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payment_his_stripe__0d3c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['stripe_invoice_id'], name='payment_his_stripe__0d6dde_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['mercadopago_payment_id'], name='payment_his_mercado_afa45a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['invoice_number'], name='payment_his_invoice_befd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['status', 'transaction_date'], name='payment_his_status_ad7ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['created_at', 'status'], name='payment_his_created_54f037_idx'),
        ),
    ]
