# Generated by Django 5.1.6 on 2025-08-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_simplify_company_model'),
        ('companies', '0008_company_companies_subscri_f72d81_idx_and_more'),
    ]

    operations = [
    ]
