# Generated by Django 4.2.11 on 2025-11-06 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Insight Configuration',
                'verbose_name_plural': 'AI Insight Configurations',
                'db_table': 'ai_insight_configs',
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_score', models.DecimalField(decimal_places=1, help_text='Financial health score from 0 to 10', max_digits=3)),
                ('health_status', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bom'), ('regular', 'Regular'), ('poor', 'Ruim')], max_length=20)),
                ('summary', models.TextField(help_text='Executive summary of the analysis')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('alerts', models.JSONField(default=list, help_text='List of alerts: [{type, severity, title, description, recommendation}]')),
                ('opportunities', models.JSONField(default=list, help_text='List of opportunities: [{type, severity, title, description, recommendation}]')),
                ('predictions', models.JSONField(default=dict, help_text='Predictions: {next_month_cash_flow, confidence, reasoning}')),
                ('recommendations', models.JSONField(default=list, help_text='Top recommendations as list of strings')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(default=0, help_text='Number of tokens consumed by OpenAI API')),
                ('model_version', models.CharField(default='gpt-4o-mini', help_text='OpenAI model version used', max_length=50)),
                ('analysis_data', models.JSONField(help_text='Snapshot of the data sent to AI for analysis')),
                ('has_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', '-generated_at'], name='ai_insights_user_id_41439f_idx'), models.Index(fields=['user', 'period_start', 'period_end'], name='ai_insights_user_id_ef13be_idx')],
            },
        ),
    ]
