# Generated by Django 5.1.6 on 2025-08-12 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_insights', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='companies.company'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aicredit',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credits', to='companies.company'),
        ),
        migrations.AddField(
            model_name='aicredittransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='companies.company'),
        ),
        migrations.AddField(
            model_name='aicredittransaction',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_insights.aiconversation'),
        ),
        migrations.AddField(
            model_name='aicredittransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='companies.company'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_insights', to='ai_insights.aiconversation'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_insights.aiconversation'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_insights', to='ai_insights.aimessage'),
        ),
        migrations.AddField(
            model_name='aicredittransaction',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_insights.aimessage'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['company', 'status', '-updated_at'], name='ai_conversa_company_8067a7_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', '-updated_at'], name='ai_conversa_user_id_0309df_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_messages_convers_15163f_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['company', 'status', '-created_at'], name='ai_insights_company_65a941_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['type', 'priority', '-created_at'], name='ai_insights_type_7006cf_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['status', 'expires_at'], name='ai_insights_status_887b55_idx'),
        ),
        migrations.AddIndex(
            model_name='aicredittransaction',
            index=models.Index(fields=['company', '-created_at'], name='ai_credit_t_company_e2a77f_idx'),
        ),
        migrations.AddIndex(
            model_name='aicredittransaction',
            index=models.Index(fields=['type', 'created_at'], name='ai_credit_t_type_b25369_idx'),
        ),
    ]
