# Generated by Django 5.1.6 on 2025-08-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0003_add_encrypted_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='financial_context',
            field=models.JSONField(default=dict, help_text='Snapshot dos dados financeiros', verbose_name='contexto financeiro'),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='data_context',
            field=models.JSONField(default=dict, help_text='Dados que geraram o insight', verbose_name='contexto de dados'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Dados para renderizar gráficos, tabelas, etc', null=True, verbose_name='dados estruturados'),
        ),
    ]
