# Generated by Django 5.1.6 on 2025-08-24 03:50
# CLEAN VERSION - Problematic RemoveIndex operations removed

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aianalysis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aianalysistemplate',
            options={},
        ),
        # SAFE INDEX REMOVALS (indexes that exist in migration state)
        migrations.RemoveIndex(
            model_name='aianalysis',
            name='ai_analyses_company_b07452_idx',
        ),
        migrations.RemoveIndex(
            model_name='aianalysis',
            name='ai_analyses_created_0be874_idx',
        ),
        migrations.RemoveIndex(
            model_name='aianalysis',
            name='ai_analyses_cache_k_9a7c1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='aianalysis',
            name='ai_analyses_is_favo_a7a1b0_idx',
        ),
        # PROBLEMATIC INDEXES REMOVED - These cause ValueError
        # migrations.RemoveIndex(
        #     model_name='report',
        #     name='reports_company_c4b7ee_idx',  # ← CAUSES ValueError
        # ),
        # migrations.RemoveIndex(
        #     model_name='report',
        #     name='reports_created_c5f642_idx',   # ← May also cause issues
        # ),
        # migrations.RemoveIndex(
        #     model_name='report',
        #     name='reports_is_gene_3ba654_idx',   # ← May also cause issues
        # ),
        
        # FIELD REMOVALS for aianalysis model
        migrations.RemoveField(
            model_name='aianalysis',
            name='ai_response',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='analysis_config',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='analysis_type',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='cache_key',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='company',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='health_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='input_parameters',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='insights',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='predictions',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='title',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='updated_at',
        ),
        # FIELD REMOVALS for aianalysistemplate model
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='analysis_type',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='default_filters',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='default_parameters',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='output_format',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='prompt_template',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='template_config',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='aianalysistemplate',
            name='visualization_config',
        ),
        
        # ADD FIELD to Report model
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        
        # ADD NEW INDEXES (these should be safe)
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['company', 'report_type', 'created_at'], name='reports_company_fe15d9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['period_start', 'period_end'], name='reports_period__7f1873_idx'),
        ),
        
        # ALTER MODEL TABLES
        migrations.AlterModelTable(
            name='aianalysis',
            table=None,
        ),
        migrations.AlterModelTable(
            name='aianalysistemplate',
            table=None,
        ),
    ]