# Generated by Django 5.1.6 on 2025-07-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportSchedule',
        ),
    ]
