# Generated by Django 5.1.6 on 2025-07-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportschedule',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='name'),
        ),
    ]
