# Generated by Django 5.1.6 on 2025-09-01 23:41

from django.db import migrations


class Migration(migrations.Migration):
    """
    No-op migration to clear pending migration warnings.
    AI analysis models are already properly configured in 0002_clean_aianalysis_refactor.
    """

    dependencies = [
        ('reports', '0002_clean_aianalysis_refactor'),
    ]

    operations = [
        # No operations needed - models are already up to date
    ]
