# Generated by Django 5.1.6 on 2025-07-21 05:51
# Modified to remove dependency on ReportSchedule

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_max_users_field'),
        ('reports', '0002_alter_aianalysis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='template name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('analysis_type', models.CharField(choices=[('financial_health', 'Saúde Financeira'), ('cash_flow_prediction', 'Previsão de Fluxo de Caixa'), ('expense_optimization', 'Otimização de Gastos'), ('revenue_analysis', 'Análise de Receita'), ('risk_assessment', 'Avaliação de Riscos'), ('investment_advice', 'Consultoria de Investimento'), ('custom_query', 'Consulta Personalizada'), ('general_insights', 'Insights Gerais')], max_length=30, verbose_name='analysis type')),
                ('template_config', models.JSONField(default=dict, verbose_name='template configuration')),
                ('prompt_template', models.TextField(verbose_name='prompt template')),
                ('default_parameters', models.JSONField(default=dict, verbose_name='default parameters')),
                ('default_filters', models.JSONField(default=dict, verbose_name='default filters')),
                ('output_format', models.JSONField(default=dict, verbose_name='output format')),
                ('visualization_config', models.JSONField(default=list, verbose_name='visualization configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_templates', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Analysis Template',
                'verbose_name_plural': 'AI Analysis Templates',
                'db_table': 'ai_analysis_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('analysis_type', models.CharField(choices=[('financial_health', 'Saúde Financeira'), ('cash_flow_prediction', 'Previsão de Fluxo de Caixa'), ('expense_optimization', 'Otimização de Gastos'), ('revenue_analysis', 'Análise de Receita'), ('risk_assessment', 'Avaliação de Riscos'), ('investment_advice', 'Consultoria de Investimento'), ('custom_query', 'Consulta Personalizada'), ('general_insights', 'Insights Gerais')], default='general_insights', max_length=30, verbose_name='analysis type')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('analysis_config', models.JSONField(default=dict, verbose_name='analysis configuration')),
                ('input_parameters', models.JSONField(default=dict, verbose_name='input parameters')),
                ('filters', models.JSONField(default=dict, verbose_name='filters')),
                ('ai_response', models.JSONField(default=dict, verbose_name='AI response')),
                ('insights', models.JSONField(default=list, verbose_name='insights')),
                ('recommendations', models.JSONField(default=list, verbose_name='recommendations')),
                ('predictions', models.JSONField(default=dict, verbose_name='predictions')),
                ('summary', models.JSONField(default=dict, verbose_name='summary')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='confidence score')),
                ('health_score', models.FloatField(blank=True, null=True, verbose_name='health score')),
                ('risk_score', models.FloatField(blank=True, null=True, verbose_name='risk score')),
                ('is_processed', models.BooleanField(default=False, verbose_name='is processed')),
                ('processing_time', models.IntegerField(default=0, verbose_name='processing time (seconds)')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('cache_key', models.CharField(blank=True, max_length=255, verbose_name='cache key')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='is favorite')),
                ('tags', models.JSONField(default=list, verbose_name='tags')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'db_table': 'ai_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'analysis_type'], name='ai_analyses_company_b07452_idx'), models.Index(fields=['created_at'], name='ai_analyses_created_0be874_idx'), models.Index(fields=['cache_key'], name='ai_analyses_cache_k_9a7c1c_idx'), models.Index(fields=['is_favorite'], name='ai_analyses_is_favo_a7a1b0_idx')],
            },
        ),
    ]