# Generated by Django 5.1.6 on 2025-07-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportschedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='file format'),
        ),
    ]
