# Generated by Django 5.1.6 on 2025-08-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_aianalysis_options_and_more'),
        ('reports', '0003_aianalysistemplate_aianalysis'),
    ]

    operations = [
    ]
