# Generated by Django 5.1.6 on 2025-07-31 03:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionManagement',
            fields=[
            ],
            options={
                'verbose_name': 'Gestão de Assinatura',
                'verbose_name_plural': 'Gestão de Assinaturas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('companies.company',),
        ),
    ]
