# Generated by Django 5.1.6 on 2025-08-20 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_add_early_access'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='PaymentRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('exhausted', 'Exhausted'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('last_error_message', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retry_record', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.AddIndex(
            model_name='paymentretry',
            index=models.Index(fields=['status', 'next_retry_at'], name='payments_pa_status_6604a0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentretry',
            index=models.Index(fields=['payment', 'status'], name='payments_pa_payment_2bda8f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentretry',
            index=models.Index(fields=['next_retry_at'], name='payments_pa_next_re_d31e17_idx'),
        ),
    ]
