# Generated by Django 5.1.6 on 2025-08-26 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_add_early_access'),
        ('payments', '0003_add_paymentauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Unique event ID from payment gateway', max_length=255, unique=True)),
                ('source', models.CharField(choices=[('stripe', 'Stripe'), ('mercadopago', 'MercadoPago'), ('paypal', 'PayPal')], db_index=True, default='stripe', max_length=20)),
                ('event_type', models.CharField(choices=[('checkout.session.completed', 'Checkout Session Completed'), ('invoice.payment_succeeded', 'Invoice Payment Succeeded'), ('invoice.payment_failed', 'Invoice Payment Failed'), ('customer.subscription.created', 'Subscription Created'), ('customer.subscription.updated', 'Subscription Updated'), ('customer.subscription.deleted', 'Subscription Deleted'), ('payment_intent.succeeded', 'Payment Intent Succeeded'), ('payment_intent.payment_failed', 'Payment Intent Failed'), ('setup_intent.succeeded', 'Setup Intent Succeeded')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='received', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_event', models.JSONField(help_text='Raw webhook event data (sanitized)')),
                ('processed_data', models.JSONField(blank=True, help_text='Extracted/processed data from event', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='companies.company')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='payments.payment')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='payments.subscription')),
            ],
            options={
                'db_table': 'payments_webhook_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('successful', models.BooleanField(default=False)),
                ('webhook_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='payments.webhookevent')),
            ],
            options={
                'db_table': 'payments_webhook_delivery_attempt',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_id', 'source'], name='payments_we_event_i_b23b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', 'created_at'], name='payments_we_status_89e26e_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type', 'status'], name='payments_we_event_t_e14d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['company', 'created_at'], name='payments_we_company_ca7e24_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliveryattempt',
            index=models.Index(fields=['webhook_event', 'attempt_number'], name='payments_we_webhook_1ad7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliveryattempt',
            index=models.Index(fields=['successful', 'attempted_at'], name='payments_we_success_37dd5f_idx'),
        ),
    ]