# Generated by Django 5.1.6 on 2025-09-01 23:41

from django.db import migrations


class Migration(migrations.Migration):
    """
    No-op migration to clear pending migration warnings.
    PaymentAuditLog model cleanup is already handled by previous migrations.
    """

    dependencies = [
        ('payments', '0004_add_webhook_event_models'),
    ]

    operations = [
        # No operations needed - audit log cleanup already handled
    ]
