# Generated by Django 4.2.11 on 2025-09-24 01:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pluggy_item_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('UPDATING', 'Updating'), ('UPDATED', 'Updated'), ('LOGIN_ERROR', 'Login Error'), ('WAITING_USER_INPUT', 'Waiting User Input'), ('OUTDATED', 'Outdated'), ('ERROR', 'Error')], default='UPDATING', max_length=30)),
                ('status_detail', models.JSONField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('execution_status', models.CharField(blank=True, max_length=50)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('CONNECTORS', 'Connectors Sync'), ('ACCOUNTS', 'Accounts Sync'), ('TRANSACTIONS', 'Transactions Sync'), ('FULL', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='banking.bankconnection')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluggy_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_url', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(default='BR', max_length=2)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('type', models.CharField(max_length=50)),
                ('credentials_schema', models.JSONField(default=dict)),
                ('supports_mfa', models.BooleanField(default=False)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country', 'is_active'], name='banking_con_country_7eb661_idx'), models.Index(fields=['type', 'is_active'], name='banking_con_type_1097a2_idx')],
            },
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='banking.connector'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pluggy_account_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('type', models.CharField(choices=[('CHECKING', 'Checking Account'), ('SAVINGS', 'Savings Account'), ('CREDIT_CARD', 'Credit Card'), ('LOAN', 'Loan'), ('INVESTMENT', 'Investment')], max_length=20)),
                ('subtype', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency_code', models.CharField(default='BRL', max_length=3)),
                ('bank_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.bankconnection')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pluggy_transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_code', models.CharField(default='BRL', max_length=3)),
                ('date', models.DateField(db_index=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('category_id', models.CharField(blank=True, max_length=50)),
                ('payment_data', models.JSONField(blank=True, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('merchant_category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['account', 'date'], name='banking_tra_account_e2ae22_idx'), models.Index(fields=['type', 'date'], name='banking_tra_type_bc7565_idx'), models.Index(fields=['category', 'date'], name='banking_tra_categor_f47655_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['user', 'is_active'], name='banking_ban_user_id_fa5afa_idx'),
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['status', 'is_active'], name='banking_ban_status_a29709_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['connection', 'is_active'], name='banking_ban_connect_67629f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['type', 'is_active'], name='banking_ban_type_584245_idx'),
        ),
    ]
