# Generated by Django 5.1.6 on 2025-08-12 01:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluggyConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pluggy_id', models.IntegerField(db_index=True, unique=True, verbose_name='Pluggy ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('institution_url', models.URLField(blank=True, verbose_name='institution URL')),
                ('image_url', models.URLField(blank=True, verbose_name='image URL')),
                ('primary_color', models.CharField(default='#000000', max_length=7, verbose_name='primary color')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('country', models.CharField(default='BR', max_length=2, verbose_name='country')),
                ('has_mfa', models.BooleanField(default=False, verbose_name='has MFA')),
                ('has_oauth', models.BooleanField(default=False, verbose_name='has OAuth')),
                ('is_open_finance', models.BooleanField(default=False, verbose_name='is Open Finance')),
                ('is_sandbox', models.BooleanField(default=False, verbose_name='is sandbox')),
                ('products', models.JSONField(default=list, verbose_name='supported products')),
                ('credentials', models.JSONField(default=list, verbose_name='credentials schema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Pluggy Connector',
                'verbose_name_plural': 'Pluggy Connectors',
                'db_table': 'pluggy_connectors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['pluggy_id'], name='pluggy_conn_pluggy__d79f04_idx'), models.Index(fields=['type', 'country'], name='pluggy_conn_type_60ce39_idx'), models.Index(fields=['is_open_finance'], name='pluggy_conn_is_open_eaa2e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PluggyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pluggy_item_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Pluggy Item ID')),
                ('client_user_id', models.CharField(blank=True, max_length=100, verbose_name='client user ID')),
                ('webhook_url', models.URLField(blank=True, verbose_name='webhook URL')),
                ('next_auto_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='next auto sync at')),
                ('products', models.JSONField(blank=True, default=list, verbose_name='products')),
                ('parameter', models.JSONField(blank=True, default=dict, verbose_name='parameter')),
                ('encrypted_parameter', models.TextField(blank=True, default='', verbose_name='encrypted parameter')),
                ('status', models.CharField(choices=[('LOGIN_IN_PROGRESS', 'Login in Progress'), ('WAITING_USER_INPUT', 'Waiting User Input'), ('UPDATING', 'Updating'), ('UPDATED', 'Updated'), ('LOGIN_ERROR', 'Login Error'), ('OUTDATED', 'Outdated'), ('ERROR', 'Error'), ('DELETED', 'Deleted'), ('CONSENT_REVOKED', 'Consent Revoked')], default='CREATED', max_length=30, verbose_name='status')),
                ('execution_status', models.CharField(blank=True, choices=[('CREATED', 'Created'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('LOGIN_ERROR', 'Login Error'), ('INVALID_CREDENTIALS', 'Invalid Credentials'), ('USER_INPUT_TIMEOUT', 'User Input Timeout'), ('USER_AUTHORIZATION_PENDING', 'User Authorization Pending'), ('USER_AUTHORIZATION_NOT_GRANTED', 'User Authorization Not Granted'), ('SITE_NOT_AVAILABLE', 'Site Not Available'), ('ERROR', 'Error')], max_length=50, verbose_name='execution status')),
                ('pluggy_created_at', models.DateTimeField(verbose_name='Pluggy created at')),
                ('pluggy_updated_at', models.DateTimeField(verbose_name='Pluggy updated at')),
                ('last_successful_update', models.DateTimeField(blank=True, null=True, verbose_name='last successful update')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='error code')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('status_detail', models.JSONField(blank=True, default=dict, verbose_name='status detail')),
                ('consent_id', models.CharField(blank=True, max_length=100, verbose_name='consent ID')),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='consent expires at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluggy_items', to='companies.company')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='banking.pluggyconnector')),
            ],
            options={
                'verbose_name': 'Pluggy Item',
                'verbose_name_plural': 'Pluggy Items',
                'db_table': 'pluggy_items',
            },
        ),
        migrations.CreateModel(
            name='ItemWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('item.created', 'Item Created'), ('item.updated', 'Item Updated'), ('item.error', 'Item Error'), ('item.deleted', 'Item Deleted'), ('item.login_succeeded', 'Login Succeeded'), ('item.waiting_user_input', 'Waiting User Input'), ('connector.status_updated', 'Connector Status Updated'), ('transactions.created', 'Transactions Created'), ('transactions.updated', 'Transactions Updated'), ('transactions.deleted', 'Transactions Deleted'), ('consent.created', 'Consent Created'), ('consent.updated', 'Consent Updated'), ('consent.revoked', 'Consent Revoked'), ('payment_intent.created', 'Payment Intent Created'), ('payment_intent.completed', 'Payment Intent Completed'), ('payment_intent.waiting_payer_authorization', 'Payment Intent Waiting Payer Authorization'), ('payment_intent.error', 'Payment Intent Error'), ('scheduled_payment.created', 'Scheduled Payment Created'), ('scheduled_payment.completed', 'Scheduled Payment Completed'), ('scheduled_payment.error', 'Scheduled Payment Error'), ('scheduled_payment.canceled', 'Scheduled Payment Canceled'), ('payment_refund.completed', 'Payment Refund Completed'), ('payment_refund.error', 'Payment Refund Error'), ('automatic_pix_payment.created', 'Automatic PIX Payment Created'), ('automatic_pix_payment.completed', 'Automatic PIX Payment Completed'), ('automatic_pix_payment.error', 'Automatic PIX Payment Error'), ('automatic_pix_payment.canceled', 'Automatic PIX Payment Canceled')], max_length=50, verbose_name='event type')),
                ('event_id', models.CharField(max_length=100, unique=True, verbose_name='event ID')),
                ('payload', models.JSONField(verbose_name='payload')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('triggered_by', models.CharField(blank=True, choices=[('USER', 'User Action'), ('CLIENT', 'Client Action'), ('SYNC', 'Sync Process'), ('INTERNAL', 'Internal Process')], help_text='Who or what triggered this webhook event', max_length=20, verbose_name='triggered by')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='banking.pluggyitem')),
            ],
            options={
                'verbose_name': 'Item Webhook',
                'verbose_name_plural': 'Item Webhooks',
                'db_table': 'item_webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pluggy_account_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Pluggy Account ID')),
                ('type', models.CharField(choices=[('BANK', 'Bank Account'), ('CREDIT', 'Credit Card'), ('INVESTMENT', 'Investment'), ('LOAN', 'Loan'), ('OTHER', 'Other')], max_length=20, verbose_name='type')),
                ('subtype', models.CharField(blank=True, choices=[('CHECKING_ACCOUNT', 'Checking Account'), ('SAVINGS_ACCOUNT', 'Savings Account'), ('CREDIT_CARD', 'Credit Card'), ('PREPAID_CARD', 'Prepaid Card'), ('INVESTMENT_ACCOUNT', 'Investment Account'), ('LOAN_ACCOUNT', 'Loan Account'), ('OTHER', 'Other')], max_length=30, verbose_name='subtype')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='number')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('marketing_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='marketing name')),
                ('owner', models.CharField(blank=True, max_length=200, null=True, verbose_name='owner')),
                ('tax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='tax number')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='balance')),
                ('balance_in_account_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='balance in account currency')),
                ('balance_date', models.DateTimeField(blank=True, null=True, verbose_name='balance date')),
                ('currency_code', models.CharField(default='BRL', max_length=3, verbose_name='currency code')),
                ('investment_status', models.CharField(blank=True, max_length=50, verbose_name='investment status')),
                ('bank_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='bank data')),
                ('credit_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='credit data')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('pluggy_created_at', models.DateTimeField(verbose_name='Pluggy created at')),
                ('pluggy_updated_at', models.DateTimeField(verbose_name='Pluggy updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='companies.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.pluggyitem')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('both', 'Both')], max_length=20, verbose_name='type')),
                ('icon', models.CharField(default='📁', max_length=50, verbose_name='icon')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='color')),
                ('is_system', models.BooleanField(default=False, verbose_name='is system category')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_categories', to='companies.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='banking.transactioncategory')),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
                'db_table': 'transaction_categories',
                'ordering': ['type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pluggy_transaction_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Pluggy Transaction ID')),
                ('type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10, verbose_name='type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted')], default='POSTED', max_length=10, verbose_name='status')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('description_raw', models.TextField(blank=True, null=True, verbose_name='description raw')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='amount')),
                ('amount_in_account_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='amount in account currency')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='transaction balance')),
                ('currency_code', models.CharField(default='BRL', max_length=3, verbose_name='currency code')),
                ('date', models.DateTimeField(verbose_name='transaction date')),
                ('provider_code', models.CharField(blank=True, max_length=50, verbose_name='provider code')),
                ('provider_id', models.CharField(blank=True, max_length=100, verbose_name='provider ID')),
                ('merchant', models.JSONField(blank=True, default=dict, null=True, verbose_name='merchant')),
                ('payment_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='payment data')),
                ('pluggy_category_id', models.CharField(blank=True, max_length=100, verbose_name='Pluggy category ID')),
                ('pluggy_category_description', models.CharField(blank=True, max_length=200, verbose_name='Pluggy category')),
                ('operation_type', models.CharField(blank=True, max_length=50, verbose_name='operation type')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='payment method')),
                ('credit_card_metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='credit card metadata')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('tags', models.JSONField(blank=True, default=list, null=True, verbose_name='tags')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('pluggy_created_at', models.DateTimeField(verbose_name='Pluggy created at')),
                ('pluggy_updated_at', models.DateTimeField(verbose_name='Pluggy updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='companies.company')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banking.transactioncategory')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PluggyCategory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='category ID')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='parent ID')),
                ('parent_description', models.CharField(blank=True, max_length=200, verbose_name='parent description')),
                ('internal_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pluggy_mappings', to='banking.transactioncategory')),
            ],
            options={
                'verbose_name': 'Pluggy Category',
                'verbose_name_plural': 'Pluggy Categories',
                'db_table': 'pluggy_categories',
                'ordering': ['parent_description', 'description'],
            },
        ),
        migrations.AddIndex(
            model_name='pluggyitem',
            index=models.Index(fields=['company', 'status'], name='pluggy_item_company_b6d45b_idx'),
        ),
        migrations.AddIndex(
            model_name='pluggyitem',
            index=models.Index(fields=['pluggy_item_id'], name='pluggy_item_pluggy__fb4c90_idx'),
        ),
        migrations.AddIndex(
            model_name='pluggyitem',
            index=models.Index(fields=['last_successful_update'], name='pluggy_item_last_su_42e47b_idx'),
        ),
        migrations.AddIndex(
            model_name='pluggyitem',
            index=models.Index(fields=['connector', 'status'], name='pluggy_item_connect_154bab_idx'),
        ),
        migrations.AddIndex(
            model_name='itemwebhook',
            index=models.Index(fields=['item', 'event_type'], name='item_webhoo_item_id_0d7aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='itemwebhook',
            index=models.Index(fields=['processed', 'created_at'], name='item_webhoo_process_3eccc3_idx'),
        ),
        migrations.AddIndex(
            model_name='itemwebhook',
            index=models.Index(fields=['event_id'], name='item_webhoo_event_i_5c3c66_idx'),
        ),
        migrations.AddIndex(
            model_name='itemwebhook',
            index=models.Index(fields=['event_type', 'processed'], name='item_webhoo_event_t_9ceaa1_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['company', 'is_active'], name='bank_accoun_company_83bd98_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['item', 'type'], name='bank_accoun_item_id_840868_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['pluggy_account_id'], name='bank_accoun_pluggy__43b8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['type', 'is_active'], name='bank_accoun_type_3b3f83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('company', 'pluggy_account_id')},
        ),
        migrations.AddIndex(
            model_name='transactioncategory',
            index=models.Index(fields=['company', 'type', 'is_active'], name='transaction_company_544262_idx'),
        ),
        migrations.AddIndex(
            model_name='transactioncategory',
            index=models.Index(fields=['slug'], name='transaction_slug_24cebf_idx'),
        ),
        migrations.AddIndex(
            model_name='transactioncategory',
            index=models.Index(fields=['parent', 'order'], name='transaction_parent__82ba74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactioncategory',
            unique_together={('company', 'slug')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='transaction_account_f34883_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', 'date'], name='transaction_company_82ff85_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['pluggy_transaction_id'], name='transaction_pluggy__b76dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'type'], name='transaction_date_cbe8da_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['pluggy_category_id'], name='transaction_pluggy__61ec29_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'date'], name='transaction_categor_3ca96c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'status'], name='transaction_type_f4191c_idx'),
        ),
    ]
