# Generated by Django 5.1.6 on 2025-07-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialGoal',
        ),
    ]
