# Generated by Django 5.1.6 on 2025-07-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance_in_account_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='balance in account currency'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='investment_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='investment status'),
        ),
        migrations.AddField(
            model_name='pluggyitem',
            name='next_auto_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next auto sync at'),
        ),
        migrations.AddField(
            model_name='pluggyitem',
            name='parameter',
            field=models.JSONField(blank=True, default=dict, verbose_name='parameter'),
        ),
        migrations.AddField(
            model_name='pluggyitem',
            name='products',
            field=models.JSONField(blank=True, default=list, verbose_name='products'),
        ),
        migrations.AddField(
            model_name='pluggyitem',
            name='webhook_url',
            field=models.URLField(blank=True, verbose_name='webhook URL'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_in_account_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='amount in account currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='transaction balance'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description_raw',
            field=models.TextField(blank=True, verbose_name='description raw'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='provider code'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='provider ID'),
        ),
        migrations.AlterField(
            model_name='itemwebhook',
            name='event_type',
            field=models.CharField(choices=[('item.created', 'Item Created'), ('item.updated', 'Item Updated'), ('item.error', 'Item Error'), ('item.deleted', 'Item Deleted'), ('item.login_succeeded', 'Login Succeeded'), ('item.waiting_user_input', 'Waiting User Input'), ('connector.status_updated', 'Connector Status Updated'), ('transactions.created', 'Transactions Created'), ('transactions.updated', 'Transactions Updated'), ('transactions.deleted', 'Transactions Deleted'), ('consent.created', 'Consent Created'), ('consent.updated', 'Consent Updated'), ('consent.revoked', 'Consent Revoked'), ('payment_intent.created', 'Payment Intent Created'), ('payment_intent.completed', 'Payment Intent Completed'), ('payment_intent.waiting_payer_authorization', 'Payment Intent Waiting Payer Authorization'), ('payment_intent.error', 'Payment Intent Error'), ('scheduled_payment.created', 'Scheduled Payment Created'), ('scheduled_payment.completed', 'Scheduled Payment Completed'), ('scheduled_payment.error', 'Scheduled Payment Error'), ('scheduled_payment.canceled', 'Scheduled Payment Canceled'), ('payment_refund.completed', 'Payment Refund Completed'), ('payment_refund.error', 'Payment Refund Error'), ('automatic_pix_payment.created', 'Automatic PIX Payment Created'), ('automatic_pix_payment.completed', 'Automatic PIX Payment Completed'), ('automatic_pix_payment.error', 'Automatic PIX Payment Error'), ('automatic_pix_payment.canceled', 'Automatic PIX Payment Canceled')], max_length=50, verbose_name='event type'),
        ),
    ]
