# Generated by Django 5.1.6 on 2025-07-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_delete_financialgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='company',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='category',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_is_ai_c_face04_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_ai_cate_aa0b34_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ai_category_confidence',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ai_suggested_category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_ai_categorized',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_manually_reviewed',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='RecurringTransaction',
        ),
    ]
