# Generated by Django 5.0.1 on 2025-06-02 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_financialgoal_budget'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_bank_ac_7b215f_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_categor_5b779c_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_transac_348887_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('company', 'bank_provider', 'agency', 'account_number', 'account_type')},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='_access_token_encrypted',
            field=models.TextField(blank=True, verbose_name='encrypted access token'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='_refresh_token_encrypted',
            field=models.TextField(blank=True, verbose_name='encrypted refresh token'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['company', 'status'], name='bank_accoun_company_2d1d04_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank_provider', 'external_account_id'], name='bank_accoun_bank_pr_452c79_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['last_sync_at'], name='bank_accoun_last_sy_346517_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['bank_account', 'transaction_date', 'category'], name='transaction_bank_ac_bdae91_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['bank_account', 'transaction_type', 'transaction_date'], name='transaction_bank_ac_b4774b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['bank_account', 'status', 'transaction_date'], name='transaction_bank_ac_2003e9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date', 'category', 'amount'], name='transaction_transac_19a86f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['counterpart_name', 'transaction_date'], name='transaction_counter_2e0b78_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_id', 'bank_account'], name='transaction_externa_849c32_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_ai_categorized', 'category'], name='transaction_is_ai_c_face04_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ai_category_confidence', 'is_manually_reviewed'], name='transaction_ai_cate_aa0b34_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_reconciled', 'reconciled_at'], name='transaction_is_reco_dd7c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='transactioncategory',
            index=models.Index(fields=['category_type', 'is_active'], name='transaction_categor_8c0157_idx'),
        ),
        migrations.AddIndex(
            model_name='transactioncategory',
            index=models.Index(fields=['is_system', 'category_type'], name='transaction_is_syst_0a81f8_idx'),
        ),
        migrations.AddIndex(
            model_name='transactioncategory',
            index=models.Index(fields=['parent', 'order'], name='transaction_parent__82ba74_idx'),
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='refresh_token',
        ),
    ]
