# Generated by Django 5.1.6 on 2025-07-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_remove_budget_categories_remove_budget_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='sync_error_message',
            field=models.TextField(blank=True, verbose_name='sync error message'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='sync_status',
            field=models.CharField(blank=True, default='active', max_length=30, verbose_name='sync status'),
        ),
    ]
