# Generated by Django 4.2.11 on 2025-09-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_allow_null_bank_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_data',
            field=models.JSONField(default=dict),
        ),
    ]
