# Generated by Django 5.0.1 on 2025-06-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_remove_transaction_transaction_bank_ac_7b215f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='posted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='posted date'),
        ),
    ]
