# Generated by Django 5.1.6 on 2025-07-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_add_sync_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='BRL', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='account name'),
        ),
        migrations.AddField(
            model_name='bankprovider',
            name='logo_url',
            field=models.URLField(blank=True, help_text='External logo URL (e.g., from Pluggy)', verbose_name='logo URL'),
        ),
        migrations.AddField(
            model_name='bankprovider',
            name='primary_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, verbose_name='primary color'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data from Pluggy', verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='agency',
            field=models.CharField(blank=True, max_length=10, verbose_name='agency'),
        ),
    ]
