# Generated by Django 5.0.1 on 2025-01-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_add_posted_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='pluggy_item_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pluggy item ID'),
        ),
    ]