# Generated by Django 5.1.6 on 2025-07-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_bankaccount_currency_bankaccount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadata'),
        ),
    ]
