# Generated by Django 5.1.6 on 2025-07-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_pluggy_webhook_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwebhook',
            name='triggered_by',
            field=models.CharField(blank=True, choices=[('USER', 'User Action'), ('CLIENT', 'Client Action'), ('SYNC', 'Sync Process'), ('INTERNAL', 'Internal Process')], help_text='Who or what triggered this webhook event', max_length=20, verbose_name='triggered by'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
    ]
