# Generated by Django 5.0.1 on 2025-06-04 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_bankaccount_pluggy_item_id'),
        ('companies', '0002_company_subscription_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('belvo_id', models.CharField(max_length=100, unique=True, verbose_name='Belvo ID')),
                ('institution', models.CharField(max_length=100, verbose_name='Institution')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Display Name')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('unconfirmed', 'Unconfirmed'), ('token_renewal_required', 'Token Renewal Required')], default='unconfirmed', max_length=30, verbose_name='Status')),
                ('last_access_mode', models.CharField(choices=[('single', 'Single'), ('recurrent', 'Recurrent')], default='single', max_length=20, verbose_name='Last Access Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('belvo_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Belvo Created At')),
                ('belvo_created_by', models.CharField(blank=True, max_length=100, verbose_name='Belvo Created By')),
                ('refresh_rate', models.IntegerField(default=86400, verbose_name='Refresh Rate')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='External ID')),
                ('credentials_stored', models.BooleanField(default=False, verbose_name='Credentials Stored')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bank_connections', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Bank Connection',
                'verbose_name_plural': 'Bank Connections',
                'db_table': 'bank_connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='bank_connec_company_2360ff_idx'), models.Index(fields=['belvo_id'], name='bank_connec_belvo_i_0b92eb_idx'), models.Index(fields=['institution'], name='bank_connec_institu_d686cf_idx')],
            },
        ),
    ]
