# Generated by Django 5.1.6 on 2025-07-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_bankaccount_pluggy_item_id'),
    ]

    operations = [
        # Remove BankConnection table if it exists (from removed Belvo integration)
        migrations.RunSQL(
            "DROP TABLE IF EXISTS bank_connections;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
