# Generated by Django 5.1.6 on 2025-07-31 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_add_consent_model'),
        ('banking', '0006_add_webhook_improvements'),
    ]

    operations = [
    ]
