# Generated by Django 5.1.6 on 2025-07-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_auto_20250710_0417'),
    ]

    operations = [
        # Rename external_account_id to external_id for consistency
        migrations.RunSQL(
            "ALTER TABLE bank_accounts RENAME COLUMN external_account_id TO external_id;",
            reverse_sql="ALTER TABLE bank_accounts RENAME COLUMN external_id TO external_account_id;",
        ),
    ]
