# Generated by Django 5.1.6 on 2025-07-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_add_metadata_to_bankaccount'),
        ('companies', '0008_company_companies_subscri_f72d81_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('company', 'external_id')},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='agency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='agency'),
        ),
    ]
