# Generated by Django 4.2.11 on 2025-10-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_transaction_category_refactor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='banking_tra_pluggy__05816c_idx',
            old_name='banking_tra_pluggy__c44c0e_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='banking_tra_user_ca_431d8b_idx',
            old_name='banking_tra_user_ca_a7b9c3_idx',
        ),
    ]
