# Generated by Django 5.1.6 on 2025-07-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_simplify_bank_account_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankprovider',
            name='is_open_finance',
            field=models.BooleanField(default=False, help_text='Se este provedor é um conector Open Finance'),
        ),
    ]
