# Generated by Django 5.1.6 on 2025-07-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_merge_20250730_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consent',
        ),
    ]
