# Generated by Django 4.2.11 on 2025-10-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_add_credit_fields_to_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='available_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Available credit limit for credit cards', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total credit limit for credit cards', max_digits=15, null=True),
        ),
    ]
