# Generated by Django 4.2.11 on 2025-10-29 21:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0009_add_credit_card_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('payable', 'A Pagar'), ('receivable', 'A Receber')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency_code', models.CharField(default='BRL', max_length=3)),
                ('due_date', models.DateField(db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('partially_paid', 'Parcialmente Pago'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('recurrence', models.CharField(choices=[('once', 'Uma vez'), ('monthly', 'Mensal'), ('weekly', 'Semanal'), ('yearly', 'Anual')], default='once', max_length=20)),
                ('installment_number', models.IntegerField(blank=True, help_text='Installment number for recurring bills', null=True)),
                ('customer_supplier', models.CharField(blank=True, help_text='Name of customer (for receivables) or supplier (for payables)', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='banking.category')),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_bills', to='banking.transaction')),
                ('parent_bill', models.ForeignKey(blank=True, help_text='For recurring bills, links to the original bill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='banking.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'type', 'status'], name='banking_bil_user_id_23e276_idx'), models.Index(fields=['user', 'due_date'], name='banking_bil_user_id_1aa154_idx'), models.Index(fields=['status', 'due_date'], name='banking_bil_status_965bfb_idx')],
            },
        ),
    ]
