# Generated by Django 5.1.6 on 2025-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_sync_external_id_state'),
        ('companies', '0004_paymentmethod_paymenthistory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='bank_accoun_bank_pr_452c79_idx',
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank_provider', 'external_id'], name='bank_accoun_bank_pr_097377_idx'),
        ),
    ]
