# Generated by Django 5.1.6 on 2025-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_remove_bankaccount_bank_accoun_bank_pr_452c79_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Conta Corrente'), ('savings', 'Conta Poupança'), ('business', 'Conta Empresarial'), ('digital', 'Conta Digital'), ('credit_card', 'Cartão de Crédito')], max_length=20, verbose_name='account type'),
        ),
    ]
