# Generated by Django 4.2.11 on 2025-11-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankconnection',
            name='status',
            field=models.CharField(choices=[('UPDATING', 'Updating'), ('UPDATED', 'Updated'), ('LOGIN_ERROR', 'Login Error'), ('WAITING_USER_INPUT', 'Waiting User Input'), ('WAITING_USER_ACTION', 'Waiting User Action'), ('OUTDATED', 'Outdated'), ('ERROR', 'Error')], default='UPDATING', max_length=30),
        ),
    ]
