# Generated by Django 4.2.11 on 2025-12-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='linked_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_bill', to='banking.transaction'),
        ),
    ]
