# Generated by Django 5.1.6 on 2025-08-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_add_encrypted_parameter'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='banking_tra_acc_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='banking_tra_type_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='banking_tra_cat_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='banking_tra_complex_idx',
        ),
    ]
