# Generated by Django 5.1.6 on 2025-07-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_bankconnection'),
        ('banking', '0011_add_credit_card_type'),
    ]

    operations = [
    ]
