# Generated by Django 5.1.6 on 2025-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_allow_null_json_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluggyitem',
            name='status',
            field=models.CharField(
                choices=[
                    ('LOGIN_IN_PROGRESS', 'Login in Progress'),
                    ('WAITING_USER_INPUT', 'Waiting User Input'),
                    ('UPDATING', 'Updating'),
                    ('UPDATED', 'Updated'),
                    ('LOGIN_ERROR', 'Login Error'),
                    ('OUTDATED', 'Outdated'),
                    ('ERROR', 'Error'),
                    ('DELETED', 'Deleted'),
                    ('CONSENT_REVOKED', 'Consent Revoked'),
                ],
                default='CREATED',
                max_length=30,
                verbose_name='status'
            ),
        ),
    ]
