# Generated by Django 5.1.6 on 2025-07-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_merge_0006_bankconnection_0011_add_credit_card_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankConnection',
        ),
    ]
