# Generated by Django 5.1.6 on 2025-07-26 01:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0014_fix_pluggy_connector_pk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccountold',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bankaccountold',
            name='bank_provider',
        ),
        migrations.RemoveField(
            model_name='bankaccountold',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transactionold',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='banksync',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='transactionold',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transactionold',
            name='reconciled_by',
        ),
        migrations.RemoveField(
            model_name='transactionold',
            name='subcategory',
        ),
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='bank_accoun_company_b50c34_idx',
            old_name='bank_accoun_company_4e5fa2_idx',
        ),
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='bank_accoun_item_id_dfc104_idx',
            old_name='bank_accoun_item_id_b7b9c3_idx',
        ),
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='bank_accoun_pluggy__fa5c32_idx',
            old_name='bank_accoun_pluggy__0e6e87_idx',
        ),
        migrations.RenameIndex(
            model_name='itemwebhook',
            new_name='item_webhoo_item_id_0d7aaf_idx',
            old_name='item_webhoo_item_id_fef4d6_idx',
        ),
        migrations.RenameIndex(
            model_name='itemwebhook',
            new_name='item_webhoo_process_90ae2b_idx',
            old_name='item_webhoo_process_2f8c59_idx',
        ),
        migrations.RenameIndex(
            model_name='itemwebhook',
            new_name='item_webhoo_event_i_5c3c66_idx',
            old_name='item_webhoo_event_i_2e8baa_idx',
        ),
        migrations.RenameIndex(
            model_name='pluggyitem',
            new_name='pluggy_item_company_b6d45b_idx',
            old_name='pluggy_item_company_06c7ff_idx',
        ),
        migrations.RenameIndex(
            model_name='pluggyitem',
            new_name='pluggy_item_pluggy__0cf5fe_idx',
            old_name='pluggy_item_pluggy__d5b22e_idx',
        ),
        migrations.RenameIndex(
            model_name='pluggyitem',
            new_name='pluggy_item_last_su_42e47b_idx',
            old_name='pluggy_item_last_su_8e5a65_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_account_0a557c_idx',
            old_name='transaction_account_25e589_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_pluggy__145547_idx',
            old_name='transaction_pluggy__1e5c65_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_date_e2ef16_idx',
            old_name='transaction_date_d5ad25_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_pluggy__6425da_idx',
            old_name='transaction_pluggy__0e8b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_categor_60e5b6_idx',
            old_name='transaction_categor_9f5c48_idx',
        ),
        migrations.RemoveField(
            model_name='pluggyitem',
            name='id',
        ),
        migrations.AddField(
            model_name='pluggyitem',
            name='item_pluggy_id',
            field=models.CharField(db_index=True, default=1, max_length=100, unique=True, verbose_name='Pluggy Item ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pluggyconnector',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pluggyconnector',
            name='pluggy_id',
            field=models.IntegerField(db_column=True, unique=True, verbose_name='Pluggy ID'),
        ),
        migrations.AlterField(
            model_name='pluggyitem',
            name='pluggy_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='BankProvider',
        ),
        migrations.DeleteModel(
            name='BankAccountOld',
        ),
        migrations.DeleteModel(
            name='BankSync',
        ),
        migrations.DeleteModel(
            name='TransactionOld',
        ),
    ]
