# Generated by Django 5.1.6 on 2025-07-26 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0015_alter_bankaccountold_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluggyitem',
            name='connector',
            field=models.ForeignKey(db_column='connector_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='banking.pluggyconnector', to_field='pluggy_id'),
        ),
    ]
