# Generated by Django 4.2.11 on 2026-01-03 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0015_transaction_user_subcategory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billpayment',
            new_name='banking_bil_bill_id_bc4ddb_idx',
            old_name='banking_bil_bill_id_paymen_idx',
        ),
        migrations.RenameIndex(
            model_name='categoryrule',
            new_name='banking_cat_user_id_7c9e11_idx',
            old_name='banking_cat_user_id_6a5b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='banking_tra_user_su_f24c20_idx',
            old_name='banking_tra_user_su_idx',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='custom_name',
            field=models.CharField(blank=True, default='', help_text='User-defined custom name for this account', max_length=200),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
